/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'editorial-briefs': EditorialBrief;
    'brief-items': BriefItem;
    providers: Provider;
    'collected-items': CollectedItem;
    'generated-pieces': GeneratedPiece;
    'piece-assignments': PieceAssignment;
    'qa-verdicts': QaVerdict;
    'brief-files': BriefFile;
    'channel-configs': ChannelConfig;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'editorial-briefs': EditorialBriefsSelect<false> | EditorialBriefsSelect<true>;
    'brief-items': BriefItemsSelect<false> | BriefItemsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    'collected-items': CollectedItemsSelect<false> | CollectedItemsSelect<true>;
    'generated-pieces': GeneratedPiecesSelect<false> | GeneratedPiecesSelect<true>;
    'piece-assignments': PieceAssignmentsSelect<false> | PieceAssignmentsSelect<true>;
    'qa-verdicts': QaVerdictsSelect<false> | QaVerdictsSelect<true>;
    'brief-files': BriefFilesSelect<false> | BriefFilesSelect<true>;
    'channel-configs': ChannelConfigsSelect<false> | ChannelConfigsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'news-hq-settings': NewsHqSetting;
  };
  globalsSelect: {
    'news-hq-settings': NewsHqSettingsSelect<false> | NewsHqSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'editor';
  /**
   * External cms-prod channel ids this user leads. Empty = leads nothing.
   */
  leadOfDesks?: string[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-briefs".
 */
export interface EditorialBrief {
  id: string;
  title: string;
  channel: string;
  channelName?: string | null;
  uploadedBy: string | User;
  sourceType: 'paste' | 'docx' | 'pdf';
  /**
   * Unused — original PDF/DOCX files are not stored; only extracted text is kept.
   */
  sourceFile?: (string | null) | BriefFile;
  /**
   * The exact text that was parsed — pasted or extracted client-side from a PDF/DOCX.
   */
  rawText: string;
  status: 'draft' | 'parsed' | 'confirmed' | 'superseded';
  /**
   * Immutable snapshot of the first LLM parse, captured before any lead edits.
   */
  rawParseSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  version: number;
  previousVersion?: (string | null) | EditorialBrief;
  confirmedBy?: (string | null) | User;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brief-files".
 */
export interface BriefFile {
  id: string;
  channel: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brief-items".
 */
export interface BriefItem {
  id: string;
  brief: string | EditorialBrief;
  topic: string;
  /**
   * Bold section header from the brief (e.g. INTERNATIONAL NEWS, GAZA & PALESTINE).
   */
  sectionTitle?: string | null;
  /**
   * Piece format from the brief (News, Video, Infographic, Op-Ed, Feature, …).
   */
  format?: string | null;
  keywords?: string[] | null;
  angle?: string | null;
  priorityOrder?: number | null;
  region?: string | null;
  /**
   * Angles or sub-topics to leave uncovered.
   */
  exclusions?: string[] | null;
  sentiment?: string | null;
  portrayalNotes?: string | null;
  /**
   * Specific words/phrases the piece must not use.
   */
  bannedTerms?: string[] | null;
  requiredContext?: string | null;
  /**
   * The normalized query string sent to providers for this item.
   */
  query?: string | null;
  status: 'pending' | 'queried' | 'no-results' | 'error';
  lastQueryRunAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: string;
  name: string;
  type: 'newsHq' | 'eventRegistry';
  enabled?: boolean | null;
  baseUrl: string;
  /**
   * Wire agencies to include.
   */
  agencies?: string[] | null;
  /**
   * Name of the env var holding the API key - never store the key itself here.
   */
  apiKeyEnvVar?: string | null;
  /**
   * External cms-prod channel ids this provider serves. Empty = all channels (typical for global NewsHQ).
   */
  channels?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collected-items".
 */
export interface CollectedItem {
  id: string;
  briefItem: string | BriefItem;
  /**
   * Same-story items from different providers share this key.
   */
  groupKey?: string | null;
  headline: string;
  body: string;
  language: string;
  /**
   * NewsHQ hits start as candidates; editors select or reject each source.
   */
  reviewStatus: 'candidate' | 'selected' | 'rejected';
  sources: {
    provider: string | Provider;
    providerItemId: string;
    sourceUrl?: string | null;
    publishTimestamp: string;
    rawPayload?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-pieces".
 */
export interface GeneratedPiece {
  id: string;
  collectedItem: string | CollectedItem;
  /**
   * Denormalized from collectedItem.briefItem.brief for cheap full-chain traceability.
   */
  brief: string | EditorialBrief;
  channel: string;
  channelName?: string | null;
  /**
   * ContentBlock[] as first generated - immutable once written.
   */
  generatedSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * ContentBlock[] - the editor's live, mutable working copy.
   */
  currentBody?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attributionString: string;
  sourceOnly?: boolean | null;
  /**
   * Shown when sourceOnly is set.
   */
  restrictionReason?: string | null;
  publishedAt?: string | null;
  /**
   * The id createArticle() returned from trt-global-cms-prod. Unused while CMS publish is stubbed.
   */
  cmsPackageId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piece-assignments".
 */
export interface PieceAssignment {
  id: string;
  piece: string | GeneratedPiece;
  assignedTo: string | User;
  /**
   * Empty when the editor self-claimed rather than being assigned by a manager.
   */
  assignedBy?: (string | null) | User;
  previousAssignee?: (string | null) | User;
  status: 'claimed' | 'inProgress' | 'inQA' | 'verdictReached' | 'awaitingApproval' | 'approved' | 'published';
  claimedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa-verdicts".
 */
export interface QaVerdict {
  id: string;
  /**
   * Not unique - a piece accumulates one verdict per QA run, preserving history.
   */
  piece: string | GeneratedPiece;
  /**
   * ContentBlock[] as it stood when this verdict was issued.
   */
  pieceBodySnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  verdict: 'goodToGo' | 'needsAttention' | 'rejected';
  /**
   * Git ref/tag of the okf-ruleset bundle that ran, e.g. a commit sha or tag.
   */
  okfVersion: string;
  flags?:
    | {
        /**
         * The ContentBlock this flag applies to - never the document as a whole.
         */
        blockId: string;
        rule: string;
        severity: 'hardFail' | 'softFail';
        message: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Docs-style QA notes: highlight quote + message for editors. Separate from automated flags.
   */
  suggestions?:
    | {
        quote: string;
        message: string;
        severity: 'softFail' | 'hardFail';
        /**
         * Hidden from QA UI — anchors the highlight to a ContentBlock.
         */
        blockId: string;
        startOffset: number;
        endOffset: number;
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  submittedBy: string | User;
  submittedAt: string;
  overridden?: boolean | null;
  overrideJustification?: string | null;
  overriddenBy?: (string | null) | User;
  overriddenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channel-configs".
 */
export interface ChannelConfig {
  id: string;
  channel: string;
  channelName?: string | null;
  /**
   * e.g. 'English', 'Russian' - the language generation writes in.
   */
  language: string;
  /**
   * Event Registry language code, e.g. 'eng', 'rus'.
   */
  erLang?: string | null;
  /**
   * Matches a filename under okf-ruleset/guidelines/ (without .md). Empty = no desk-specific guideline.
   */
  guidelineSlug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'editorial-briefs';
        value: string | EditorialBrief;
      } | null)
    | ({
        relationTo: 'brief-items';
        value: string | BriefItem;
      } | null)
    | ({
        relationTo: 'providers';
        value: string | Provider;
      } | null)
    | ({
        relationTo: 'collected-items';
        value: string | CollectedItem;
      } | null)
    | ({
        relationTo: 'generated-pieces';
        value: string | GeneratedPiece;
      } | null)
    | ({
        relationTo: 'piece-assignments';
        value: string | PieceAssignment;
      } | null)
    | ({
        relationTo: 'qa-verdicts';
        value: string | QaVerdict;
      } | null)
    | ({
        relationTo: 'brief-files';
        value: string | BriefFile;
      } | null)
    | ({
        relationTo: 'channel-configs';
        value: string | ChannelConfig;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  leadOfDesks?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-briefs_select".
 */
export interface EditorialBriefsSelect<T extends boolean = true> {
  title?: T;
  channel?: T;
  channelName?: T;
  uploadedBy?: T;
  sourceType?: T;
  sourceFile?: T;
  rawText?: T;
  status?: T;
  rawParseSnapshot?: T;
  version?: T;
  previousVersion?: T;
  confirmedBy?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brief-items_select".
 */
export interface BriefItemsSelect<T extends boolean = true> {
  brief?: T;
  topic?: T;
  sectionTitle?: T;
  format?: T;
  keywords?: T;
  angle?: T;
  priorityOrder?: T;
  region?: T;
  exclusions?: T;
  sentiment?: T;
  portrayalNotes?: T;
  bannedTerms?: T;
  requiredContext?: T;
  query?: T;
  status?: T;
  lastQueryRunAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  enabled?: T;
  baseUrl?: T;
  agencies?: T;
  apiKeyEnvVar?: T;
  channels?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collected-items_select".
 */
export interface CollectedItemsSelect<T extends boolean = true> {
  briefItem?: T;
  groupKey?: T;
  headline?: T;
  body?: T;
  language?: T;
  reviewStatus?: T;
  sources?:
    | T
    | {
        provider?: T;
        providerItemId?: T;
        sourceUrl?: T;
        publishTimestamp?: T;
        rawPayload?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-pieces_select".
 */
export interface GeneratedPiecesSelect<T extends boolean = true> {
  collectedItem?: T;
  brief?: T;
  channel?: T;
  channelName?: T;
  generatedSnapshot?: T;
  currentBody?: T;
  attributionString?: T;
  sourceOnly?: T;
  restrictionReason?: T;
  publishedAt?: T;
  cmsPackageId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piece-assignments_select".
 */
export interface PieceAssignmentsSelect<T extends boolean = true> {
  piece?: T;
  assignedTo?: T;
  assignedBy?: T;
  previousAssignee?: T;
  status?: T;
  claimedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa-verdicts_select".
 */
export interface QaVerdictsSelect<T extends boolean = true> {
  piece?: T;
  pieceBodySnapshot?: T;
  verdict?: T;
  okfVersion?: T;
  flags?:
    | T
    | {
        blockId?: T;
        rule?: T;
        severity?: T;
        message?: T;
        id?: T;
      };
  suggestions?:
    | T
    | {
        quote?: T;
        message?: T;
        severity?: T;
        blockId?: T;
        startOffset?: T;
        endOffset?: T;
        createdAt?: T;
        id?: T;
      };
  submittedBy?: T;
  submittedAt?: T;
  overridden?: T;
  overrideJustification?: T;
  overriddenBy?: T;
  overriddenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brief-files_select".
 */
export interface BriefFilesSelect<T extends boolean = true> {
  channel?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channel-configs_select".
 */
export interface ChannelConfigsSelect<T extends boolean = true> {
  channel?: T;
  channelName?: T;
  language?: T;
  erLang?: T;
  guidelineSlug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-hq-settings".
 */
export interface NewsHqSetting {
  id: string;
  /**
   * Wire agencies to include (values from NewsHQ /filters). Empty = all agencies for the search language.
   */
  agencies?: string[] | null;
  /**
   * NewsHQ priority filter values, e.g. 1,2,3,4.
   */
  priorities?: string[] | null;
  /**
   * Fallback NewsHQ lang when the desk has no language mapping.
   */
  defaultLang?: string | null;
  /**
   * Max sources kept per topic after ranking + LLM (capped at 5). NewsHQ is queried with limit 50 across multiple keyword layers.
   */
  limit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-hq-settings_select".
 */
export interface NewsHqSettingsSelect<T extends boolean = true> {
  agencies?: T;
  priorities?: T;
  defaultLang?: T;
  limit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}